### ISSUE TITLE
与botvs类似

### ISSUE THREAD

**Issue by shenglinqian** [miaolz123/samaritan#24]
你好，我发现您的项目与botvs的界面和语法都挺类似，你们之间是有什么关系么？

**Comment by tongxiaofeng** [comment]
应该没有任何关系。

**Comment by miaolz123** [comment]
@shenglinqian 试玩过 BotVS，个人觉得是一个很好的模式，为量化圈子提供了一种新的思路，非常佩服和感谢！

**Comment by tongxiaofeng** [comment]
这个项目后续开发的计划是什么呢？

**Comment by miaolz123** [comment]
@tongxiaofeng 完善交易所类型的支持，加入回测功能。
